version: "3.9"

services:
  db:
    image: postgres:15
    container_name: sso
    environment:
      POSTGRES_USER: sso
      POSTGRES_PASSWORD: sso
      POSTGRES_DB: sso
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
