services:
  api:
    container_name: sso-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9196:3000"
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: sso-db
    environment:
      POSTGRES_USER: sso
      POSTGRES_PASSWORD: sso
      POSTGRES_DB: sso
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
